#!/bin/bash
read -p "Enter your area or continent: " wax;
read -p "Enter your city: " wax1;
wax1="ln -sf /usr/share/zoneinfo/${wax}/${wax1} /etc/localtime";
$wax1;
hwclock --systohc --utc;
hmm="nano /etc/locale.gen";
$hmm;
locale-gen;
read -p "Enter your device name: " wax;
echo "${wax}" >> /etc/hostname;
ans="127.0.0.1\tlocalhost\n::t\t\tlocalhost\n127.0.1.1\t${wax}.localdomain\t${wax}";
printf $ans >> /etc/hosts;
passwd;
read -p "Enter the username: " wax;
wax1="useradd -m ${wax}";
$wax1;
wax1="passwd ${wax}";
$wax1;
wax1="usermod -aG wheel,audio,video,optical,storage ${wax}";
$wax1;
EDITOR=nano visudo;
pacman -S grub
read -p "Is the installation UEFI: " lok;
if [[ $lok -eq 1 ]]
then
  pacman -S efibootmgr dosfstools os-prober mtools;
  hmm="mkdir /boot/EFI";
  $hmm;
  read -p "Enter your efi partition: " eff;
  hmm="mount ${eff} /boot/EFI";
  $hmm;
  grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck;
else
  read -p "Enter the installation disk: " eff;
  pio="grub-install ${eff}"
sleep 20;  
hmm="grub-mkconfig -o /boot/grub/grub.cfg";
$hmm;
pacman -S networkmanager lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings xorg git cinnamon terminator;
systemctl enable NetworkManager;
systemctl enable lightdm;
echo "Thanks for running!";
