#!/bin/bash
ping -c 5 gnu.org;
read -p "Did you see any output: " ans;
if [[ $ans -eq 0 ]]
then
	echo "It seems that you don't have internet. Make sure you have access to internet. ";
	exit 0;
fi
timedatectl set-ntp true;
timedatectl status;
read -p "Is the time setting okay: " ans;
if [[ $ans -eq 0 ]]
then
	echo "please, try to fix it later";
fi
lsblk;
read -p "Enter your disk name: " wow;
wax="cfdisk ${wow}";
$wax;
read -p "Enter your efi partition number: " eff;
wax="mkfs.fat -F32 ${wow}${eff}";
$wax;
read -p "Enter your swap partition number: " wax;
wax1="mkswap ${wow}${wax}";
$wax1;
wax1="swapon ${wow}${wax}";
$wax1;
sleep 5;
read -p "Enter your root partition number: " wax;
wax1="mkfs.ext4 ${wow}${wax}";
$wax1;
sleep 10;
wax1="mount ${wow}${wax} /mnt";
$wax1;
hmm="pacstrap /mnt base base-devel linux-lts linux-lts-headers linux-firmware nano sudo";
$hmm;
hmm="genfstab -U /mnt >> /mnt/etc/fstab";
$hmm;
echo "Thanks for running! Now run the second script";
hmm="arch-chroot /mnt";
$hmm
