#!/bin/bash
ping -c 5 gnu.org;
sleep 5;
read -p "Did you see any output: " ans;
if [[ $ans -eq 0 ]]
then
	echo "It seems that you don't have internet. Make sure you have access to internet. ";
	exit 0;
fi
timedatectl set-ntp true;
timedatectl status;
read -p "Is the time setting okay: " ans;
if [[ $ans -eq 0 ]]
then
	echo "please, try to fix it later";
fi
lsblk;
read -p "Enter your disk name: " wow;
wax="cfdisk ${wow}";
$wax;
read -p "Enter your efi partition number: " eff;
if [[ $eff -eq 0 ]]
then
	echo "no efi partition found!"
else
	wax="mkfs.fat -F32 ${wow}${eff}";
	$wax;
fi
read -p "Enter your swap partition number: " wax;
if [[ $wax -eq 0 ]]
then
	echo "no swap partition found!"
else
	wax1="mkswap ${wow}${wax}";
	$wax1;
	wax1="swapon ${wow}${wax}";
	$wax1;
	sleep 5;
fi
read -p "Enter your root partition number: " wax;
wax1="mkfs.ext4 ${wow}${wax}";
$wax1;
sleep 10;
read -p "Enter your home partition number: " wax2;
if [[ $wax2 -eq 0 ]]
then
	echo "No home partition found!"
else
	wax1="mkfs.ext4 ${wow}${wax2}";
	$wax1;
fi
wax1="mount ${wow}${wax} /mnt";
$wax1;
if [[ $wax2 -ne 0 ]]
then
	wax1="mkdir /mnt/home";
	$wax1;
	wax3="mount ${wow}${wax2} /mnt/home";
	$wax3;
fi
lsblk;
read -p "Is everything okay? " sure;
if [[ $sure -eq 0 ]]
then
	echo "Something went wrong. Please set the things manually from now on";
	exit 0;
fi
hmm="pacstrap -i /mnt base base-devel linux-lts linux-lts-headers linux-firmware nano sudo";
$hmm;
hmm="genfstab -U /mnt >> /mnt/etc/fstab";
$hmm;
echo "Thanks for running! Now run the second script";
hmm="arch-chroot /mnt /bin/bash";
$hmm
